[en]
contentDir = "content/english"
copyright = "©2022 Grit Technologies Limited, All Rights Reserved."
footer_content = "Augmenting Technologies to Life & Systems"
footer_menu_left = "Company"
footer_menu_middle = "Domains"
footer_menu_right = "Resources"
languageName = "En"
title = "Grit Technologies Limited"
weight = 1
