[en]
contentDir = "content/english"
copyright = "Copyright@Grit Technologies Limited"
footer_content = "Augmenting Technologies to Life"
footer_menu_left = "Company"
footer_menu_middle = "Product"
footer_menu_right = "Support"
languageName = "En"
title = "Grit Technologies Limited"
weight = 1
